Course2-RailsWithActiveRecord/assignment_apps/todolistsM4/config/routes.rb
Rails.application.routes.draw do

  root to: 'todo_lists#index'

  resources :todo_lists do
    resources :todo_items, only: [:new, :create, :show, :edit, :update, :destroy]
  end

  resources :sessions, only: [:new, :create, :destroy]

 
  
  get "/login" => "sessions#new", as: "login"
  delete "/logout" => "sessions#destroy", as: "logout"

end

Course2-RailsWithActiveRecord/assignment_apps/todolistsM4/app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  validate :at_least_one_is_not_empty
  validates :gender, inclusion: { in: %w(male female) }
  validate :first_name_not_sue

  def at_least_one_is_not_empty
  	if first_name.nil? and last_name.nil?
  		errors.add(:first_name, "is nill")
  		errors.add(:last_name, "is nill")
  	end  	
  end

  def first_name_not_sue
  	if first_name == "Sue" and gender == "male"
  		errors.add(:first_name, "can't be Sue")
  	end
  end

  def self.get_all_profiles2(min, max)
  	where("birth_year BETWEEN :min_age AND :max_age", min_age: min, max_age: max).order(:birth_year)
  end

  scope :get_all_profiles, -> (min, max){ where("birth_year BETWEEN :min_age AND :max_age", min_age: "#{min}", max_age: "#{max}").order(:birth_year) }
end

Course2-RailsWithActiveRecord/assignment_apps/todolistsM4/app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list

  default_scope { order :due_date }
end

Course2-RailsWithActiveRecord/assignment_apps/todolistsM4/app/models/todo_list.rb
class TodoList < ActiveRecord::Base
	belongs_to :user
	has_many :todo_items, dependent: :destroy

	default_scope { order :list_due_date }
end

Course2-RailsWithActiveRecord/assignment_apps/todolistsM4/app/models/user.rb
class User < ActiveRecord::Base
	has_one :profile, dependent: :destroy
	has_many :todo_lists, dependent: :destroy
	has_many :todo_items, through: :todo_lists, source: :todo_items, dependent: :destroy

	has_secure_password

	validates :username, presence: true

	def get_completed_count
		todo_items.where(completed: true).count
	end
end

Course2-RailsWithActiveRecord/assignment_apps/todolistsM4/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :ensure_login
  helper_method :logged_in?, :current_user

  protected
  def ensure_login
  	redirect_to login_path unless session[:user_id]
  end
  
  def logged_in?
  	session[:user_id] # nil if false
  end
  
  def current_user
  	@current_user = User.find_by(id: session[:user_id])
  end
end

Course2-RailsWithActiveRecord/assignment_apps/todolistsM4/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_before_action :ensure_login, only: [:new, :create]
  def new
  	# Login page - new.html.erb
  end

  def create
  	user = User.find_by(username: params[:user][:username])
  	password = params[:user][:password]

  	if user && user.authenticate(password)
  		session[:user_id] = user.id
  		redirect_to root_path, notice: "Logged in successfully"
  	else
  		redirect_to login_path, alert: "Invalid username/password combination"
  	end
  end

  def destroy
  	reset_session # wipe out session and everything in it
  	redirect_to login_path, notice: "You have been logged out"
  end
end

Course2-RailsWithActiveRecord/assignment_apps/todolistsM4/app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list
  before_action :set_todo_item, only: [:show, :edit, :update, :destroy]

  # GET /todo_items
  # GET /todo_items.json
  # def index
  #   @todo_items = TodoItem.all
  # end

  # GET /todo_items/1
  # GET /todo_items/1.json
  def show
  end

  # GET /todo_items/new
  def new
    @todo_item = @todo_list.todo_items.new
    # @todo_item = TodoItem.new
  end

  # GET /todo_items/1/edit
  def edit
  end

  # POST /todo_items
  # POST /todo_items.json
  def create
    @todo_item = @todo_list.todo_items.new(todo_item_params)
    #@todo_item = TodoItem.new(todo_item_params)

    respond_to do |format|
      # may be @todo_list.save
      if @todo_item.save
        format.html { redirect_to @todo_list, notice: 'Todo item was successfully created.' }
        # format.html { redirect_to @todo_item, notice: 'Todo item was successfully created.' }
        format.json { render :show, status: :created, location: @todo_item }
      else
        format.html { render :new }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_items/1
  # PATCH/PUT /todo_items/1.json
  def update
    respond_to do |format|
      if @todo_item.update(todo_item_params)
        format.html { redirect_to @todo_list, notice: 'Todo item was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_item }
      else
        format.html { render :edit }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_items/1
  # DELETE /todo_items/1.json
  def destroy
    @todo_item.destroy
    respond_to do |format|
      format.html { redirect_to @todo_list, notice: 'Todo item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_item
      @todo_item = @todo_list.todo_items.find(params[:id])
      # @todo_item = TodoItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_item_params
      params.require(:todo_item).permit(:title, :due_date, :description, :completed)
    end

    def set_todo_list
      @todo_list = TodoList.find(params[:todo_list_id])
    end

end

Course2-RailsWithActiveRecord/assignment_apps/todolistsM4/app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = current_user.todo_lists.paginate(page: params[:page], per_page: 8)
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = current_user.todo_lists.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = current_user.todo_lists.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = current_user.todo_lists.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:list_name, :list_due_date)
    end
end

Course2-RailsWithActiveRecord/assignment_apps/todolistsM4/app/helpers/application_helper.rb
module ApplicationHelper
end

Course2-RailsWithActiveRecord/assignment_apps/todolistsM4/app/helpers/sessions_helper.rb
module SessionsHelper
end

Course2-RailsWithActiveRecord/assignment_apps/todolistsM4/app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

Course2-RailsWithActiveRecord/assignment_apps/todolistsM4/app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

Course2-RailsWithActiveRecord/assignment_apps/todolistsM4/app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list) do |f| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% @todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :list_name %><br>
    <%= f.text_field :list_name %>
  </div>
  <div class="field">
    <%= f.label :list_due_date %><br>
    <%= f.date_select :list_due_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Course2-RailsWithActiveRecord/assignment_apps/todolistsM4/app/views/todo_lists/edit.html.erb
<h1>Editing Todo List</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

Course2-RailsWithActiveRecord/assignment_apps/todolistsM4/app/views/todo_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Todo Lists</h1>

<table>
  <thead>
    <tr>
      <th>List name</th>
      <th>List due date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_lists.each do |todo_list| %>
      <tr>
        <td><%= todo_list.list_name %></td>
        <td><%= todo_list.list_due_date %></td>
        <td><%= link_to 'Show', todo_list %></td>
        <td><%= link_to 'Edit', edit_todo_list_path(todo_list) %></td>
        <td><%= link_to 'Destroy', todo_list, method: :delete %></td>
        <!-- , data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @todo_lists %>

<br>

<%= link_to 'New Todo list', new_todo_list_path %>

Course2-RailsWithActiveRecord/assignment_apps/todolistsM4/app/views/todo_lists/new.html.erb
<h1>New Todo List</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_lists_path %>

Course2-RailsWithActiveRecord/assignment_apps/todolistsM4/app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>List name:</strong>
  <%= @todo_list.list_name %>
</p>

<p>
  <strong>List due date:</strong>
  <%= @todo_list.list_due_date %>
</p>



<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Due date</th>
      <th>Description</th>
      <th>Completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_list.todo_items.each do |todo_item| %>
      <tr>
        <td><%= todo_item.title %></td>
        <td><%= todo_item.due_date %></td>
        <td><%= todo_item.description %></td>
        <td><%= todo_item.completed %></td>
        <td><%= link_to 'Show', [@todo_list, todo_item] %></td>
        <td><%= link_to 'Destroy', [@todo_list, todo_item], method: :delete %></td>
        <!-- , data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Todo Item', new_todo_list_todo_item_path(@todo_list) %> | 
<!-- , method: :new --> 
<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
<%= link_to 'Back', todo_lists_path %>